# Generated by Django 2.1.7 on 2019-05-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loguser',
            old_name='discription',
            new_name='description',
        ),
    ]
