# Generated by Django 2.1.7 on 2019-05-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20190511_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loguser',
            name='slug',
        ),
        migrations.AlterField(
            model_name='loguser',
            name='user_name',
            field=models.SlugField(max_length=20),
        ),
    ]
