# Generated by Django 2.2.1 on 2019-06-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogUser',
            new_name='Account',
        ),
    ]
