# Generated by Django 2.2.1 on 2019-06-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190603_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='user_name',
            new_name='account_id',
        ),
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.SlugField(default='ass', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GroupUser',
        ),
        migrations.AddField(
            model_name='groupaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Account'),
        ),
        migrations.AddField(
            model_name='groupaccount',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
        ),
    ]
