# Generated by Django 2.1.7 on 2019-06-04 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190604_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group', to_field='group_id')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Account', to_field='account_id')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupaccount',
            name='account',
        ),
        migrations.RemoveField(
            model_name='groupaccount',
            name='group',
        ),
        migrations.DeleteModel(
            name='GroupAccount',
        ),
    ]
