# Generated by Django 2.2.1 on 2019-06-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190603_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Account', to_field='account_id'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
