# Generated by Django 2.2.1 on 2019-06-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190603_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='description',
        ),
    ]
