# Generated by Django 2.1.7 on 2019-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190604_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='group_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='member_id',
            field=models.CharField(max_length=20),
        ),
    ]
