# Generated by Django 2.1.7 on 2019-06-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190604_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group', to_field='group_id'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Account', to_field='account_id'),
        ),
    ]
