# Generated by Django 2.2.1 on 2019-06-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_account_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='admin',
            new_name='admin_id',
        ),
    ]
