# Generated by Django 2.2.1 on 2019-06-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190603_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin_id',
        ),
    ]
