# Generated by Django 2.1.7 on 2019-06-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190604_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin_id',
        ),
    ]
