# Generated by Django 2.1.7 on 2019-06-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_group_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Account', to_field='account_id'),
        ),
    ]
