# Generated by Django 2.2.1 on 2019-06-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_group_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(default='asd', on_delete=django.db.models.deletion.CASCADE, to='main.Account'),
            preserve_default=False,
        ),
    ]
