# Generated by Django 2.2.1 on 2019-06-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
    ]
