# Generated by Django 2.1.7 on 2019-06-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190604_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='admin',
            new_name='admin_fk',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='group',
            new_name='group_fk',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='member',
            new_name='member_fk',
        ),
    ]
