# Generated by Django 2.1.7 on 2019-06-05 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190605_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('account_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Account')),
                ('group_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group')),
            ],
        ),
    ]
