# Generated by Django 2.1.7 on 2019-06-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='payer_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payer_fk_name', to='main.Account'),
        ),
        migrations.AlterField(
            model_name='record',
            name='account_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_fk_name', to='main.Account'),
        ),
    ]
