# Generated by Django 2.1.7 on 2019-06-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190606_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
