# Generated by Django 2.1.7 on 2019-06-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190609_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcoefficient',
            name='record_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Record'),
        ),
    ]
