# Generated by Django 2.1.7 on 2019-06-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190609_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.IntegerField()),
                ('member_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Account')),
                ('record_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Record')),
            ],
        ),
        migrations.RemoveField(
            model_name='recordcoefficient',
            name='member_fk',
        ),
        migrations.RemoveField(
            model_name='recordcoefficient',
            name='record_fk',
        ),
        migrations.DeleteModel(
            name='RecordCoefficient',
        ),
    ]
