# Generated by Django 2.1.7 on 2019-06-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190609_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
