# Generated by Django 2.1.7 on 2019-06-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190610_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('creditor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='main.Account')),
                ('debtor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='main.Account')),
                ('group_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group')),
            ],
        ),
    ]
