# Generated by Django 2.1.7 on 2019-06-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_pays'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pays',
            new_name='Pay',
        ),
        migrations.AddField(
            model_name='record',
            name='record_type',
            field=models.CharField(default='payment', max_length=10),
        ),
    ]
