# Generated by Django 2.1.7 on 2019-06-28 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_auto_20190627_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(default='payment', max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('cost', models.FloatField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField(default=0)),
                ('expense_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Expense')),
            ],
        ),
        migrations.RemoveField(
            model_name='pay',
            name='creditor_fk',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='debtor_fk',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='group_fk',
        ),
        migrations.RemoveField(
            model_name='record',
            name='account_fk',
        ),
        migrations.RemoveField(
            model_name='record',
            name='group_fk',
        ),
        migrations.RemoveField(
            model_name='record',
            name='payer_fk',
        ),
        migrations.RemoveField(
            model_name='recordratio',
            name='member_fk',
        ),
        migrations.RemoveField(
            model_name='recordratio',
            name='record_fk',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='RecordRatio',
        ),
        migrations.AddField(
            model_name='expenseratio',
            name='member_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='adder_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adder_fk', to='main.Account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='group_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payer_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer_fk', to='main.Account'),
        ),
        migrations.AddField(
            model_name='balancedetail',
            name='creditor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor', to='main.Account'),
        ),
        migrations.AddField(
            model_name='balancedetail',
            name='debtor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor', to='main.Account'),
        ),
        migrations.AddField(
            model_name='balancedetail',
            name='group_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
        ),
    ]
