# Generated by Django 2.2.1 on 2019-06-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_account_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
