# Generated by Django 2.1.7 on 2019-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_group_group_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancedetail',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
